#!/usr/bin/env python3
"""build_index: build index/unified-index.json over both entry classes.

Reads:

  entries/*.yaml                    the internal meta-models (MMDG nodes).
  external/external-standards.csv   the external standards (generated by
                                    import_external), one row per standard.
  facets/industry.yaml              the industry facet vocabulary (required).
  facets/clusters.yaml              the cluster facet vocabulary (optional).
  facets/compositional-roles.yaml   the compositional-role vocabulary (optional).
  facets/link-types.yaml            the link-type vocabulary (optional).

Writes:

  index/unified-index.json          a deterministic object with a generated_from
                                    note, totals, facet histograms, and a sorted
                                    list of minimal per-entry records.

Both entry classes carry two orthogonal facet axes: cluster (what a thing is)
and industry (which sector uses or governs it). Internal entries take their
facets from their entry file; external standards inherit industry from their
Group through the group-industry map (already materialised in the generated CSV
as the Industry column). External standards also carry a compositional role
(R1 to R8) and a default link type from the source catalogue.

The build is deterministic and idempotent: no wall clock, no random, every map
and list is sorted by a stable key, the JSON is emitted with sorted keys, two
space indent and a trailing newline. Referenced facet codes are validated
against the vocabularies that are present; a missing optional vocabulary turns
its validation off but never changes the emitted bytes for a fixed input.

Runtime dependencies: Python 3 standard library plus PyYAML. No others.
"""

import argparse
import csv
import glob
import json
import os
import re
import sys
from collections import Counter

try:
    import yaml
except ImportError as exc:  # pragma: no cover - environment guard
    sys.stderr.write("FAIL: PyYAML is required (pip install pyyaml): " + str(exc) + "\n")
    raise

GENERATED_FROM = (
    "entries/*.yaml (internal) and external/external-standards.csv (external), "
    "faceted by facets/industry.yaml, facets/clusters.yaml, "
    "facets/compositional-roles.yaml and facets/link-types.yaml. "
    "Deterministic build (no timestamps): re-running yields byte-identical output."
)

FACET_ORDER = ("by_industry", "by_cluster", "by_role", "by_origin", "by_link_type")

_SLUG_RE = re.compile(r"[^a-z0-9]+")


def registry_root(explicit=None):
    if explicit:
        return os.path.abspath(explicit)
    here = os.path.dirname(os.path.abspath(__file__))
    return os.path.abspath(os.path.join(here, os.pardir))


def fail(message):
    sys.stderr.write("FAIL: " + message + "\n")
    raise SystemExit(1)


def slugify(text):
    slug = _SLUG_RE.sub("-", (text or "").strip().lower()).strip("-")
    return slug


def load_yaml(path):
    with open(path, "r", encoding="utf-8") as handle:
        return yaml.safe_load(handle)


def load_vocab_codes(path, list_key, required, label):
    """Return the set of codes from a facet vocabulary, or None if absent.

    When required is True a missing file is fatal. When it is False a missing
    file returns None (validation for that axis is turned off).
    """
    if not os.path.isfile(path):
        if required:
            fail(label + " vocabulary not found: " + path)
        return None
    doc = load_yaml(path)
    if not isinstance(doc, dict) or not isinstance(doc.get(list_key), list):
        fail(label + " vocabulary is malformed (expected a " + list_key + " list): " + path)
    codes = set()
    for item in doc[list_key]:
        if isinstance(item, dict) and "code" in item:
            codes.add(str(item["code"]))
    if not codes:
        fail(label + " vocabulary declares no codes: " + path)
    return codes


def as_str_list(value):
    """Normalise an optional facet field into a list of non-empty strings."""
    if value is None:
        return []
    if isinstance(value, str):
        value = [value]
    if not isinstance(value, (list, tuple)):
        return []
    out = []
    for item in value:
        text = str(item).strip()
        if text:
            out.append(text)
    return out


def read_internal(root):
    """Return a list of raw internal records read from entries/*.yaml."""
    directory = os.path.join(root, "entries")
    if not os.path.isdir(directory):
        fail("entries directory not found: " + directory)
    paths = sorted(
        glob.glob(os.path.join(directory, "*.yaml"))
        + glob.glob(os.path.join(directory, "*.yml"))
    )
    records = []
    for path in paths:
        data = load_yaml(path)
        if not isinstance(data, dict):
            fail("entry is not a mapping: " + path)
        ref = data.get("id")
        if not ref:
            fail("entry has no id: " + path)
        rec = {
            "ref": str(ref),
            "origin": "internal",
            "name": str(data.get("name", data.get("id"))),
            "industry": sorted(set(as_str_list(data.get("industry")))),
            "cluster": sorted(set(as_str_list(data.get("cluster")))),
        }
        records.append(rec)
    return records


def read_external(root):
    """Return a list of raw external records read from the generated CSV."""
    path = os.path.join(root, "external", "external-standards.csv")
    if not os.path.isfile(path):
        fail(
            "external-standards.csv not found: " + path
            + " (run tools/import_external.py first)"
        )
    raw = []
    with open(path, "r", encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        if reader.fieldnames is None:
            fail("external-standards.csv has no header row: " + path)
        for required in ("Group", "Name", "Acronym", "Industry"):
            if required not in reader.fieldnames:
                fail("external-standards.csv is missing the required column " + repr(required))
        for record in reader:
            raw.append(record)

    # Assign a stable, unique ref to each external row. The base ref is the
    # slug of the Acronym, or of the Name when the Acronym is empty. Collisions
    # are broken deterministically in (Group, Acronym, Name) order by appending
    # -2, -3, and so on, so a fixed input always yields the same refs.
    raw.sort(key=lambda r: (
        (r.get("Group") or ""),
        (r.get("Acronym") or ""),
        (r.get("Name") or ""),
    ))
    used = set()
    records = []
    for record in raw:
        acronym = (record.get("Acronym") or "").strip()
        name = (record.get("Name") or "").strip()
        base = slugify(acronym) or slugify(name)
        if not base:
            base = "standard"
        ref = base
        suffix = 2
        while ref in used:
            ref = base + "-" + str(suffix)
            suffix += 1
        used.add(ref)

        role = (record.get("CompositionalRole") or "").strip()
        link_type = (record.get("DefaultLinkType") or "").strip()
        group = (record.get("Group") or "").strip()
        industry = [c for c in (record.get("Industry") or "").split(";") if c.strip()]
        industry = sorted(set(c.strip() for c in industry))

        rec = {
            "ref": ref,
            "origin": "external",
            "name": name,
            "industry": industry,
            "cluster": [],
        }
        if role:
            rec["role"] = role
        if link_type:
            rec["link_type"] = link_type
        if group:
            rec["group"] = group
        records.append(rec)
    return records


def validate_codes(records, industry_codes, cluster_codes, role_codes, link_codes):
    problems = []
    for rec in records:
        where = rec["origin"] + " " + rec["ref"]
        if industry_codes is not None:
            for code in rec.get("industry", []):
                if code not in industry_codes:
                    problems.append(where + ": unknown industry code " + repr(code))
        if cluster_codes is not None:
            for code in rec.get("cluster", []):
                if code not in cluster_codes:
                    problems.append(where + ": unknown cluster code " + repr(code))
        if role_codes is not None and "role" in rec:
            if rec["role"] not in role_codes:
                problems.append(where + ": unknown compositional role " + repr(rec["role"]))
        if link_codes is not None and "link_type" in rec:
            if rec["link_type"] not in link_codes:
                problems.append(where + ": unknown link type " + repr(rec["link_type"]))
    if problems:
        listing = "\n    ".join(sorted(set(problems)))
        fail("facet code validation failed:\n    " + listing)


def build_histograms(records):
    by_industry = Counter()
    by_cluster = Counter()
    by_role = Counter()
    by_origin = Counter()
    by_link_type = Counter()
    for rec in records:
        for code in rec.get("industry", []):
            by_industry[code] += 1
        for code in rec.get("cluster", []):
            by_cluster[code] += 1
        if "role" in rec:
            by_role[rec["role"]] += 1
        by_origin[rec["origin"]] += 1
        if "link_type" in rec:
            by_link_type[rec["link_type"]] += 1

    def sorted_map(counter):
        return {key: counter[key] for key in sorted(counter)}

    return {
        "by_industry": sorted_map(by_industry),
        "by_cluster": sorted_map(by_cluster),
        "by_role": sorted_map(by_role),
        "by_origin": sorted_map(by_origin),
        "by_link_type": sorted_map(by_link_type),
    }


def order_record(rec):
    """Return a record with a stable key order for a minimal index entry."""
    out = {
        "ref": rec["ref"],
        "origin": rec["origin"],
        "name": rec["name"],
        "industry": rec.get("industry", []),
        "cluster": rec.get("cluster", []),
    }
    if "role" in rec:
        out["role"] = rec["role"]
    if "link_type" in rec:
        out["link_type"] = rec["link_type"]
    if "group" in rec:
        out["group"] = rec["group"]
    return out


def main(argv=None):
    parser = argparse.ArgumentParser(description="Build index/unified-index.json over internal and external entries")
    parser.add_argument("--root", default=None, help="registry root directory (default: parent of tools/)")
    args = parser.parse_args(argv)

    root = registry_root(args.root)
    facets_dir = os.path.join(root, "facets")

    industry_codes = load_vocab_codes(
        os.path.join(facets_dir, "industry.yaml"), "industries", True, "industry")
    cluster_codes = load_vocab_codes(
        os.path.join(facets_dir, "clusters.yaml"), "clusters", False, "cluster")
    role_codes = load_vocab_codes(
        os.path.join(facets_dir, "compositional-roles.yaml"), "roles", False, "compositional-role")
    link_codes = load_vocab_codes(
        os.path.join(facets_dir, "link-types.yaml"), "link_types", False, "link-type")

    internal = read_internal(root)
    external = read_external(root)
    records = internal + external

    validate_codes(records, industry_codes, cluster_codes, role_codes, link_codes)

    histograms = build_histograms(records)

    entries = [order_record(rec) for rec in records]
    entries.sort(key=lambda r: (r["ref"], r["origin"]))

    index = {
        "generated_from": GENERATED_FROM,
        "totals": {
            "internal": len(internal),
            "external": len(external),
            "total": len(records),
        },
        "facets": histograms,
        "entries": entries,
    }

    out_dir = os.path.join(root, "index")
    if not os.path.isdir(out_dir):
        os.makedirs(out_dir)
    out_path = os.path.join(out_dir, "unified-index.json")
    with open(out_path, "w", encoding="utf-8", newline="\n") as handle:
        json.dump(index, handle, sort_keys=True, indent=2, ensure_ascii=False)
        handle.write("\n")

    sys.stdout.write(
        "wrote " + out_path + ": " + str(len(records)) + " entries ("
        + str(len(internal)) + " internal, " + str(len(external)) + " external)\n"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
